version: '3'
services:
  app:
    build: .
    ports:
      - "16254:16254"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./database/dev.db
    volumes:
      - ./prisma/database/:/usr/src/app/data
    env_file:
        - .env